Attraction.delete_all
Location.delete_all
Country.delete_all

Location.create!([
  {city_name: "Dallas", state_province: "TX", country: "USA", description: "This city right here!"},
  {city_name: "London", state_province: "England", country: "United Kingdom", description: "Our former countrymen"},
  {city_name: "Miami", state_province: "FL", country: "USA", description: "A city in Southern Florida. "},
  {city_name: "Birmingham", state_province: "AL", country: "USA", description: nil},
  {city_name: "Los Angeles", state_province: "CA", country: "USA", description: nil},
  {city_name: "San Diego", state_province: "CA", country: "USA", description: nil},
  {city_name: "St. Louis", state_province: "MO", country: "USA", description: nil},
  {city_name: "Orlando", state_province: "FL", country: "USA", description: nil},
  {city_name: "Yerevan", state_province: "Yerevan", country: "Armenia", description: ""},
  {city_name: 'Hanoi', state_province: '', country: 'Vietnam' },
  {city_name: 'Tokyo', state_province: '', country: 'Japan'},
])


Attraction.create!([
  {name: "Dealey Plaza", type_of: 2, address: "Dealey Plaza, Dallas, TX, United States", latitude: "32.7788: 48", longitude: "-96.808299", description: "The place that Dallas is most \"known\" for", user_id: 4 },
  {name: "Eiffel Tower", type_of: 2, address: "Eiffel Tower, Paris, France", latitude: "48.85837", longitude: "2.294481", description: "The big radio tower in the middle of Paris", user_id: 4 },
  {name: "Parent's House", type_of: 4, address: "4113 Pineridge Dr., Garland, TX", latitude: "32.915222", longitude: "-96.694894", description: "Where I grew up. Just using this as a test to make sure the user_id column is properly filled in.", user_id: 4 },
  {name: "Jeremy's House", type_of: 0, address: "102 Beechwood Pl., Lewisville, TX, USA", latitude: "33.043749", longitude: "-97.029711", description: "This is the house where much of this application was written.", user_id: 4},
  {name: "Great Ocean Road", type_of: 3, address: "Great Ocean Road, Melbourne, Australia", description: nil, user_id: 3 },
  {name: "Tennis Center", type_of: 2, address: "Tennis Center, Melbourne, Australia", description: nil, user_id: 3 },
  {name: "Great Barrier Reef", type_of: 3, address: "Great Barrier Reef, Cairns, Australia", description: nil, user_id: 3 },
  {name: "Sydney Opera House", type_of: 2, address: "Sydney Opera House, Sydney, Australia", description: nil, user_id: 3 },
  {name: "Hillside Brau", type_of: 0, address: "Hillside Brau, Salzburn, Austria", description: nil, user_id: 3 },
  {name: "Angkor Wat", type_of: 2, address: "Angkor Wat, Siem Reap, Cambodia", description: nil, user_id: 3 },
  {name: "Pub Street", type_of: 6, address: "Pub Street, Siem Reap, Cambodia", description: nil, user_id: 3 },
  {name: "The Wallace Gallery", type_of: 2, address: "The Wallace Gallery, London, England", description: nil, user_id: 3 },
  {name: "Borough Market", type_of: 0, address: "Borough Market, London, England", description: nil, user_id: 3 },
  {name: "Tate Modern", type_of: 2, address: "Tate Modern, London, England", description: nil, user_id: 3 },
  {name: "Westminster Abbey", type_of: 2, address: "Westminster Abbey, London, England", description: nil, user_id: 3 },
  {name: "Rudas Baths", type_of: 5, address: "Rudas Baths, Budapest, Hungary", description: nil, user_id: 3 },
  {name: "Robot Cabaret", type_of: 6, address: "Robot Cabaret, Tokyo, Japan", description: nil, user_id: 3 },
  {name: "Tsukiji Fish Market", type_of: 6, address: "Tsukiji Fish Market, Tokyo, Japan", description: nil, user_id: 3 },
  {name: "Meiji Shrine", type_of: 2, address: "Meiji Shrine, Tokyo, Japan", description: nil, user_id: 3 },
  {name: "Park Hyatt Bar", type_of: 6, address: "Park Hyatt Bar, Tokyo, Japan", description: nil, user_id: 3 },
  {name: "Yamazaki Distillery", type_of: 0, address: "Yamazaki Distillery, Kyoto, Japan", description: nil, user_id: 3 },
  {name: "Hotel Shilla", type_of: 4, address: "Hotel Shilla, Seoul, South Korea", description: nil, user_id: 3 },
  {name: "Ghandi House", type_of: 2, address: "Ghandi House, Mumbai, India", description: nil, user_id: 3 },
  {name: "Pagodas", type_of: 2, address: "Pagodas, Bagan, Myanmar", description: nil, user_id: 3 },
  {name: "Star Beam", type_of: 2, address: "Star Beam, Bagan, Myanmar", description: nil, user_id: 3 },
  {name: "Eyeful Restaurant", type_of: 0, address: "Eyeful Restaurant, Inle Lake, Myanmar", description: nil, user_id: 3 },
  {name: "De Rokery", type_of: 6, address: "De Rokery, Amsterdam, Netherlands", description: nil, user_id: 3 },
  {name: "Besseggen", type_of: 3, address: "Besseggen, Besseggen, Norway", description: nil, user_id: 3 },
  {name: "Trolltunga", type_of: 3, address: "Trolltunga, Trolltunga, Norway", description: nil, user_id: 3 },
  {name: "Plaza de Armas", type_of: 2, address: "Plaza de Armas, Cusco, Peru", description: nil, user_id: 3 },
  {name: "Alpaca Expeditions", type_of: 7, address: "Alpaca Expeditions, Machu Picchu, Peru", description: nil, user_id: 3 },
  {name: "Marina Bay Sands", type_of: 6, address: "Marina Bay Sands, Singapore, Singapore", description: nil, user_id: 3 },
  {name: "Chinatown Open Food Plaza", type_of: 0, address: "Chinatown Open Food Plaza, Singapore, Singapore", description: nil, user_id: 3 },
  {name: "Bike Around", type_of: 3, address: "Bike Around, Singapore, Singapore", description: nil, user_id: 3 },
  {name: "Las Ramblas", type_of: 0, address: "Las Ramblas, Barcelona, Spain", description: nil, user_id: 3 },
  {name: "Mount Pilatus", type_of: 3, address: "Mount Pilatus, Zurich, Switzerland", description: nil, user_id: 3 },
  {name: "Hang Gliding Interlaken", type_of: 3, address: "Hang Gliding Interlaken, Interlaken, Switzerland", description: nil, user_id: 3 },
  {name: "Tamsui along the coast", type_of: 3, address: "Tamsui along the coast, Taipei, Taiwan", description: nil, user_id: 3 },
  {name: "Ximin Night Market", type_of: 0, address: "Ximin Night Market, Taipei, Taiwan", description: nil, user_id: 3 },
  {name: "Beitou Hot Springs", type_of: 5, address: "Beitou Hot Springs, Taipei, Taiwan", description: nil, user_id: 3 },
  {name: "Taipei 101", type_of: 4, address: "Taipei 101, Taipei, Taiwan", description: nil, user_id: 3 },
  {name: "Coco van Bike", type_of: 3, address: "Coco van Bike, Bangkok, Thailand", description: nil, user_id: 3 },
  {name: "Rajas Fashion", type_of: 4, address: "Rajas Fashion, Bangkok, Thailand", description: nil, user_id: 3 },
  {name: "Somboon Siam Square One", type_of: 0, address: "Somboon Siam Square One, Putamwan, Bangkok, Thailand", description: nil, user_id: 3 },
  {name: "Gondola Serenade", type_of: 2, address: "Gondola Serenade, Venice, Italy", description: nil, user_id: 3 },
  {name: "Exotic Food Tour", type_of: 0, address: "Exotic Food Tour, Hanoi, Vietnam", description: nil, user_id: 3 },
  {name: "Old Quarter Bia Hoi", type_of: 0, address: "Old Quarter Bia Hoi, Hanoi, Vietnam", description: nil, user_id: 3 },
  {name: "Indochina Sails Cruise", type_of: 3, address: "Inodchina Sails Cruise, Hanoi, Vietnam", description: nil, user_id: 3 }
])
Country.create!([
  {name: "USA"},
  {name: "Afghanistan"},
  {name: "Albania"},
  {name: "Algeria"},
  {name: "American Samoa"},
  {name: "Andorra"},
  {name: "Angola"},
  {name: "Anguilla"},
  {name: "Antarctica"},
  {name: "Antigua and Barbuda"},
  {name: "Argentina"},
  {name: "Armenia"},
  {name: "Aruba"},
  {name: "Australia"},
  {name: "Austria"},
  {name: "Azerbaijan"},
  {name: "Bahamas"},
  {name: "Bahrain"},
  {name: "Bangladesh"},
  {name: "Barbados"},
  {name: "Belarus"},
  {name: "Belgium"},
  {name: "Belize"},
  {name: "Benin"},
  {name: "Bermuda"},
  {name: "Bhutan"},
  {name: "Bolivia"},
  {name: "Bosnia and Herzegovina"},
  {name: "Botswana"},
  {name: "Bouvet Island"},
  {name: "Brazil"},
  {name: "British Antarctic Territory"},
  {name: "British Indian Ocean Territory"},
  {name: "British Virgin Islands"},
  {name: "Brunei"},
  {name: "Bulgaria"},
  {name: "Burkina Faso"},
  {name: "Burundi"},
  {name: "Cambodia"},
  {name: "Cameroon"},
  {name: "Canada"},
  {name: "Canton and Enderbury Islands"},
  {name: "Cape Verde"},
  {name: "Cayman Islands"},
  {name: "Central African Republic"},
  {name: "Chad"},
  {name: "Chile"},
  {name: "China"},
  {name: "Christmas Island"},
  {name: "Cocos [Keeling] Islands"},
  {name: "Colombia"},
  {name: "Comoros"},
  {name: "Congo - Brazzaville"},
  {name: "Congo - Kinshasa"},
  {name: "Cook Islands"},
  {name: "Costa Rica"},
  {name: "Croatia"},
  {name: "Cuba"},
  {name: "Cyprus"},
  {name: "Czech Republic"},
  {name: "Côte d’Ivoire"},
  {name: "Denmark"},
  {name: "Djibouti"},
  {name: "Dominica"},
  {name: "Dominican Republic"},
  {name: "Dronning Maud Land"},
  {name: "Ecuador"},
  {name: "Egypt"},
  {name: "El Salvador"},
  {name: "Equatorial Guinea"},
  {name: "Eritrea"},
  {name: "Estonia"},
  {name: "Ethiopia"},
  {name: "Falkland Islands"},
  {name: "Faroe Islands"},
  {name: "Fiji"},
  {name: "Finland"},
  {name: "France"},
  {name: "French Guiana"},
  {name: "French Polynesia"},
  {name: "French Southern Territories"},
  {name: "French Southern and Antarctic Territories"},
  {name: "Gabon"},
  {name: "Gambia"},
  {name: "Georgia"},
  {name: "Germany"},
  {name: "Ghana"},
  {name: "Gibraltar"},
  {name: "Greece"},
  {name: "Greenland"},
  {name: "Grenada"},
  {name: "Guadeloupe"},
  {name: "Guam"},
  {name: "Guatemala"},
  {name: "Guernsey"},
  {name: "Guinea"},
  {name: "Guinea-Bissau"},
  {name: "Guyana"},
  {name: "Haiti"},
  {name: "Heard Island and McDonald Islands"},
  {name: "Honduras"},
  {name: "Hong Kong"},
  {name: "Hungary"},
  {name: "Iceland"},
  {name: "India"},
  {name: "Indonesia"},
  {name: "Iran"},
  {name: "Iraq"},
  {name: "Ireland"},
  {name: "Isle of Man"},
  {name: "Israel"},
  {name: "Italy"},
  {name: "Jamaica"},
  {name: "Japan"},
  {name: "Jersey"},
  {name: "Johnston Island"},
  {name: "Jordan"},
  {name: "Kazakhstan"},
  {name: "Kenya"},
  {name: "Kiribati"},
  {name: "Kuwait"},
  {name: "Kyrgyzstan"},
  {name: "Laos"},
  {name: "Latvia"},
  {name: "Lebanon"},
  {name: "Lesotho"},
  {name: "Liberia"},
  {name: "Libya"},
  {name: "Liechtenstein"},
  {name: "Lithuania"},
  {name: "Luxembourg"},
  {name: "Macau SAR China"},
  {name: "Macedonia"},
  {name: "Madagascar"},
  {name: "Malawi"},
  {name: "Malaysia"},
  {name: "Maldives"},
  {name: "Mali"},
  {name: "Malta"},
  {name: "Marshall Islands"},
  {name: "Martinique"},
  {name: "Mauritania"},
  {name: "Mauritius"},
  {name: "Mayotte"},
  {name: "Mexico"},
  {name: "Micronesia"},
  {name: "Midway Islands"},
  {name: "Moldova"},
  {name: "Monaco"},
  {name: "Mongolia"},
  {name: "Montenegro"},
  {name: "Montserrat"},
  {name: "Morocco"},
  {name: "Mozambique"},
  {name: "Myanmar [Burma]"},
  {name: "Namibia"},
  {name: "Nauru"},
  {name: "Nepal"},
  {name: "Netherlands"},
  {name: "Neutral Zone"},
  {name: "New Caledonia"},
  {name: "New Zealand"},
  {name: "Nicaragua"},
  {name: "Niger"},
  {name: "Nigeria"},
  {name: "Niue"},
  {name: "Norfolk Island"},
  {name: "North Korea"},
  {name: "North Vietnam"},
  {name: "Northern Mariana Islands"},
  {name: "Norway"},
  {name: "Oman"},
  {name: "Pacific Islands Trust Territory"},
  {name: "Pakistan"},
  {name: "Palau"},
  {name: "Palestinian Territories"},
  {name: "Panama"},
  {name: "Panama Canal Zone"},
  {name: "Papua New Guinea"},
  {name: "Paraguay"},
  {name: "People's Democratic Republic of Yemen"},
  {name: "Peru"},
  {name: "Philippines"},
  {name: "Pitcairn Islands"},
  {name: "Poland"},
  {name: "Portugal"},
  {name: "Puerto Rico"},
  {name: "Qatar"},
  {name: "Romania"},
  {name: "Russia"},
  {name: "Rwanda"},
  {name: "Réunion"},
  {name: "Saint Barthélemy"},
  {name: "Saint Helena"},
  {name: "Saint Kitts and Nevis"},
  {name: "Saint Lucia"},
  {name: "Saint Martin"},
  {name: "Saint Pierre and Miquelon"},
  {name: "Saint Vincent and the Grenadines"},
  {name: "Samoa"},
  {name: "San Marino"},
  {name: "Saudi Arabia"},
  {name: "Senegal"},
  {name: "Serbia"},
  {name: "Serbia and Montenegro"},
  {name: "Seychelles"},
  {name: "Sierra Leone"},
  {name: "Singapore"},
  {name: "Slovakia"},
  {name: "Slovenia"},
  {name: "Solomon Islands"},
  {name: "Somalia"},
  {name: "South Africa"},
  {name: "South Georgia and the South Sandwich Islands"},
  {name: "South Korea"},
  {name: "Spain"},
  {name: "Sri Lanka"},
  {name: "Sudan"},
  {name: "South Sudan"},
  {name: "Suriname"},
  {name: "Svalbard and Jan Mayen"},
  {name: "Swaziland"},
  {name: "Sweden"},
  {name: "Switzerland"},
  {name: "Syria"},
  {name: "São Tomé and Príncipe"},
  {name: "Taiwan"},
  {name: "Tajikistan"},
  {name: "Tanzania"},
  {name: "Thailand"},
  {name: "Timor-Leste"},
  {name: "Togo"},
  {name: "Tokelau"},
  {name: "Tonga"},
  {name: "Trinidad and Tobago"},
  {name: "Tunisia"},
  {name: "Turkey"},
  {name: "Turkmenistan"},
  {name: "Turks and Caicos Islands"},
  {name: "Tuvalu"},
  {name: "U.S. Minor Outlying Islands"},
  {name: "U.S. Miscellaneous Pacific Islands"},
  {name: "U.S. Virgin Islands"},
  {name: "Uganda"},
  {name: "Ukraine"},
  {name: "United Arab Emirates"},
  {name: "United Kingdom"},
  {name: "Unknown or Invalid Region"},
  {name: "Uruguay"},
  {name: "Uzbekistan"},
  {name: "Vanuatu"},
  {name: "Vatican City"},
  {name: "Venezuela"},
  {name: "Vietnam"},
  {name: "Wake Island"},
  {name: "Wallis and Futuna"},
  {name: "Western Sahara"},
  {name: "Yemen"},
  {name: "Zambia"},
  {name: "Zimbabwe"},
  {name: "Åland Islands"}
])
